- hosts: host1
  tasks: 
       - name: java and tomcat install
         apt: name=openjdk-8-jdk update_cache=yes
         become: yes
       - name: apache tomcat install
         apt: name=tomcat7 update_cache=yes
         become: yes

