- hosts: host1
  tasks: 
       - name: copying jar file from local to webapp 
         copy: src=/var/lib/jenkins/workspace/cpjob_toremote/my_application-1.0-SNAPSHOT.jar dest=/var/lib/tomcat8/webapps 
         

